### ISSUE TITLE
Blokovaní VPN ze strany ISP

### ISSUE THREAD

**Issue by tsusanka** [spaze/jakobejitblokaci.cz#1]
U sekce VPN:

> - Kdy nebude fungovat: pokud poskytovatel připojení bude blokovat VPN

Může ISP blokovat VPN? Pokud vím openVPN se blokuje těžko, může běžet na libovolném portu a protokolu (tcp/udp). Pokud tedy např. běží na 443 je těžko rozlišitelný od HTTPS.

Jakože přeš nějakou analýzu trafficu to asi půjde, ale není to mimo "rozumný dosah" běžného ISP?

**Comment by soukicz** [comment]
Může blokovat konkrétní VPN. V Číně se to například pravidelně řeší, když dělají "zátahy" na VPN. Samozřejmě je ale hned nahradí jiné VPN nebo prostě změní IP.

**Comment by spaze** [comment]
Díky oběma. Jestli ISP může dělat nějakou analýzu spíš záleží na tom, co si koupí za krabičku a za kolik :-) V návodu jsem nechtěl rozlišovat jak moc těžké je blokovat Tor nebo VPN, chtěl jsem možná trochu alibisticky upozornit, že nějak to možné zablokovat je, nehledě na to, jak těžké to může být.

Pokud někoho napadne, jak složitost blokování napsat jednou větou _netechnicky_, rád to do textu přidám, tohle issue do té doby zavírám.
