### ISSUE TITLE
Návod pro majitele webů, jak ztížit možnost zablokování

### ISSUE THREAD

**Issue by martinsuchan** [spaze/jakobejitblokaci.cz#2]
Mohlo by být zajímavé sestavit i podobný návod pro majitele webů, jak co možná nejvíce ztížit možnost zablokování ze strany ISP:
- HTTPS + HSTS
- DNSSEC
- ...

**Comment by spaze** [comment]
> O 6 let (a jednu "speciální operaci") později... mnoho se za tu dobu změnilo a vyzkoušelo, především na straně blokujících (blokování na úrovni DNS u ISP a případně pokus s vyřazením domén z registru)

Přemýšlím, s trochu (aktualizace: dost) posmutnělým výrazem ve tváři, co bych tam vlastně napsal. Snad jedině "Provozujte web jako Onion Service (dříve "Tor Hidden Service"), k tomu vám pomáhej Bůh a [Enterprise Onion Tool Kit](https://github.com/alecmuffett/eotk)" 😅

Sám nevím, jestli to má ještě cenu. Asi má, ale spíš někde jinde.

 V každým případě dík za nápad!
