### ISSUE TITLE
Opera VPN is not exists anymore

### ISSUE THREAD

**Issue by samm-git** [spaze/jakobejitblokaci.cz#22]
Opera discontinued to provide its vpn for free, so this item could be removed

**Comment by spaze** [comment]
They have [discontinued the real VPN](https://www.operavpn.com/) but the "VPN" in browser [is still available](https://www.opera.com/cs/computer/features/free-vpn). No mention of Opera VPN specifically, just the browser proxy, so nothing to remove.
