### ISSUE TITLE
navod pro VPN Gate

### ISSUE THREAD

**Issue by kocour** [spaze/jakobejitblokaci.cz#7]
@spaze Myslis ze by melo smysl delat step-by-step navod treba pro konfiguraci http://www.vpngate.net/en/ http://www.vpnbook.com/? Nebo klidne vyber jineho free providera, ktery je z tveho pohledu ok... vyplodil bych pak pripadne navody pro OSX a W10

**Comment by spaze** [comment]
Nějaký návod na instalaci VPN napsat chci, ale ještě jsem se nerozhodl, koho použiju jako příklad. Free providerů se trochu obávám, VPNBook je v podstatě anonymní poskytovatel (na webu není sídlo firmy, skrytý majitel domény) a to se mi doporučovat nechce, v tom moc důvěru nemám.

**Comment by bayotop** [comment]
Urcite sa bude hodit spomenut aj moznost pouzit VPN u mobilnych zariadeni (ci uz third-party appky (i.e. Freedome VPN) alebo sa odkazat na integrovane nastavenia u androidu, iOS atd. (i.e. https://support.apple.com/en-us/HT201550).

**Comment by Cuchulain** [comment]
Používám https://shadeyouvpn.com/ což je sice placená služba, ale vcelku levná a anonymní (s platbou i přes BTC) s hromadou serverů různě po světě. Mají garantováno, že vůbec nic nelogují, tak snad je to pravda :-) A jedou i přes OpenVPN, takže mi šlape v pohodě i na androidu.
